//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.mycompany.hr.definitions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "HumanResourceService", targetNamespace = "http://mycompany.com/hr/definitions", wsdlLocation = "http://localhost:8080/ws/holiday.wsdl")
public class HumanResourceService
    extends Service
{

    private final static URL HUMANRESOURCESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/holiday.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HUMANRESOURCESERVICE_WSDL_LOCATION = url;
    }

    public HumanResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HumanResourceService() {
        super(HUMANRESOURCESERVICE_WSDL_LOCATION, new QName("http://mycompany.com/hr/definitions", "HumanResourceService"));
    }

    /**
     * 
     * @return
     *     returns HumanResource
     */
    @WebEndpoint(name = "HumanResourceSoap11")
    public HumanResource getHumanResourceSoap11() {
        return (HumanResource)super.getPort(new QName("http://mycompany.com/hr/definitions", "HumanResourceSoap11"), HumanResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HumanResource
     */
    @WebEndpoint(name = "HumanResourceSoap11")
    public HumanResource getHumanResourceSoap11(WebServiceFeature... features) {
        return (HumanResource)super.getPort(new QName("http://mycompany.com/hr/definitions", "HumanResourceSoap11"), HumanResource.class, features);
    }

}
