//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.mycompany.hr.definitions;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.mycompany.hr.schemas.HolidayRequest;
import com.mycompany.hr.schemas.ObjectFactory;

@WebService(name = "HumanResource", targetNamespace = "http://mycompany.com/hr/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HumanResource {


    /**
     * 
     * @param holidayRequest
     */
    @WebMethod(operationName = "Holiday")
    @Oneway
    public void holiday(
        @WebParam(name = "HolidayRequest", targetNamespace = "http://mycompany.com/hr/schemas", partName = "HolidayRequest")
        HolidayRequest holidayRequest);

}
